// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ols.ControlCenter.Infrastructure.Persistence;

#nullable disable

namespace Ols.ControlCenter.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ols.ControlCenter.Domain.Entities.Alert", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset?>("Deadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deadline");

                    b.Property<string>("DedupeKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("dedupe_key");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("FirstTriggeredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_triggered_at");

                    b.Property<DateTimeOffset>("LastTriggeredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_triggered_at");

                    b.Property<long>("OperationId")
                        .HasColumnType("bigint")
                        .HasColumnName("operation_id");

                    b.Property<string>("ResolutionNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("resolution_note");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<long?>("ResolvedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("resolved_by_user_id");

                    b.Property<long?>("ResponsibleUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("responsible_user_id");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("risk_level");

                    b.Property<string>("RuleCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("rule_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<int>("TriggerCount")
                        .HasColumnType("integer")
                        .HasColumnName("trigger_count");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_alerts");

                    b.HasIndex("DedupeKey")
                        .IsUnique()
                        .HasDatabaseName("ix_alerts_dedupe_key");

                    b.HasIndex("OperationId")
                        .HasDatabaseName("ix_alerts_operation_id");

                    b.HasIndex("ResponsibleUserId")
                        .HasDatabaseName("ix_alerts_responsible_user_id");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_alerts_type");

                    b.HasIndex("Status", "RiskLevel")
                        .HasDatabaseName("ix_alerts_status_risk_level");

                    b.ToTable("alerts", (string)null);
                });

            modelBuilder.Entity("Ols.ControlCenter.Domain.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("action");

                    b.Property<string>("AfterJson")
                        .HasColumnType("text")
                        .HasColumnName("after_json");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("text")
                        .HasColumnName("before_json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EntityId")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("ip_address");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<string>("UserName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_logs_entity_type_entity_id");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_audit_logs_user_id_created_at");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Ols.ControlCenter.Domain.Entities.Comment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AuthorUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("author_user_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<long?>("CancelledByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("cancelled_by_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_user_id");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_cancelled");

                    b.Property<string>("Mentions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("mentions");

                    b.Property<long>("OperationId")
                        .HasColumnType("bigint")
                        .HasColumnName("operation_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_comments");

                    b.HasIndex("AuthorUserId")
                        .HasDatabaseName("ix_comments_author_user_id");

                    b.HasIndex("OperationId", "CreatedAt")
                        .HasDatabaseName("ix_comments_operation_id_created_at");

                    b.ToTable("comments", (string)null);
                });

            modelBuilder.Entity("Ols.ControlCenter.Domain.Entities.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_user_id");

                    b.Property<decimal?>("CreditLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("credit_limit");

                    b.Property<string>("Currency")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("currency");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsCritical")
                        .HasColumnType("boolean")
                        .HasColumnName("is_critical");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.HasIndex("IsCritical")
                        .HasDatabaseName("ix_customers_is_critical");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_customers_name");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("Ols.ControlCenter.Domain.Entities.DataSource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ConnectionConfigEncrypted")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("connection_config_encrypted");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("DefaultTransportType")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("default_transport_type");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<long?>("DepartmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("department_id");

                    b.Property<int>("HeaderRowIndex")
                        .HasColumnType("integer")
                        .HasColumnName("header_row_index");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("LastSyncAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sync_at");

                    b.Property<string>("LastSyncError")
                        .HasColumnType("text")
                        .HasColumnName("last_sync_error");

                    b.Property<string>("LastSyncStatus")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("last_sync_status");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("SheetName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("sheet_name");

                    b.Property<int>("SyncIntervalMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("sync_interval_minutes");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_data_sources");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_data_sources_department_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_data_sources_is_active");

                    b.ToTable("data_sources", (string)null);
                });

            modelBuilder.Entity("Ols.ControlCenter.Domain.Entities.DataSourceColumnMapping", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("DataSourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("data_source_id");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<string>("SourceColumn")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("source_column");

                    b.Property<string>("TargetField")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("target_field");

                    b.Property<string>("Transform")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("transform");

                    b.HasKey("Id")
                        .HasName("pk_data_source_column_mappings");

                    b.HasIndex("DataSourceId", "SourceColumn")
                        .IsUnique()
                        .HasDatabaseName("ix_data_source_column_mappings_data_source_id_source_column");

                    b.ToTable("data_source_column_mappings", (string)null);
                });

            modelBuilder.Entity("Ols.ControlCenter.Domain.Entities.DataSyncLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("DataSourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("data_source_id");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("message");

                    b.Property<int>("RowsFailed")
                        .HasColumnType("integer")
                        .HasColumnName("rows_failed");

                    b.Property<int>("RowsRead")
                        .HasColumnType("integer")
                        .HasColumnName("rows_read");

                    b.Property<int>("RowsUpserted")
                        .HasColumnType("integer")
                        .HasColumnName("rows_upserted");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_data_sync_logs");

                    b.HasIndex("DataSourceId", "StartedAt")
                        .HasDatabaseName("ix_data_sync_logs_data_source_id_started_at");

                    b.ToTable("data_sync_logs", (string)null);
                });

            modelBuilder.Entity("Ols.ControlCenter.Domain.Entities.Department", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("DefaultTransportType")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("default_transport_type");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_departments");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_departments_code");

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("Ols.ControlCenter.Domain.Entities.Document", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ChecklistGroup")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("checklist_group");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DocType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("doc_type");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<long>("OperationId")
                        .HasColumnType("bigint")
                        .HasColumnName("operation_id");

                    b.Property<DateTimeOffset?>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_documents");

                    b.HasIndex("OperationId", "DocType")
                        .HasDatabaseName("ix_documents_operation_id_doc_type");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("Ols.ControlCenter.Domain.Entities.KpiSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("computed_at");

                    b.Property<string>("Metrics")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metrics");

                    b.Property<DateOnly>("Period")
                        .HasColumnType("date")
                        .HasColumnName("period");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("scope");

                    b.Property<long?>("ScopeId")
                        .HasColumnType("bigint")
                        .HasColumnName("scope_id");

                    b.HasKey("Id")
                        .HasName("pk_kpi_snapshots");

                    b.HasIndex("Scope", "ScopeId", "Period")
                        .IsUnique()
                        .HasDatabaseName("ix_kpi_snapshots_scope_scope_id_period");

                    b.ToTable("kpi_snapshots", (string)null);
                });

            modelBuilder.Entity("Ols.ControlCenter.Domain.Entities.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("level");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<long?>("RelatedEntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("related_entity_id");

                    b.Property<string>("RelatedEntityType")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("related_entity_type");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("UserId", "IsRead", "CreatedAt")
                        .HasDatabaseName("ix_notifications_user_id_is_read_created_at");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("Ols.ControlCenter.Domain.Entities.Operation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("ActualArrivalDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actual_arrival_date");

                    b.Property<string>("Consignee")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("consignee");

                    b.Property<decimal?>("CostAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("cost_amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasDefaultValue("EUR")
                        .HasColumnName("currency");

                    b.Property<long?>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasDefaultValue("")
                        .HasColumnName("customer_name");

                    b.Property<int>("DelayDays")
                        .HasColumnType("integer")
                        .HasColumnName("delay_days");

                    b.Property<string>("DelayReason")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("delay_reason");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateOnly?>("DeliveryDate")
                        .HasColumnType("date")
                        .HasColumnName("delivery_date");

                    b.Property<long?>("DepartmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("department_id");

                    b.Property<string>("DestinationCity")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("destination_city");

                    b.Property<string>("DestinationCountry")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("destination_country");

                    b.Property<string>("DocumentStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("document_status");

                    b.Property<DateTimeOffset?>("Eta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("eta");

                    b.Property<DateTimeOffset?>("Etd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("etd");

                    b.Property<string>("FinanceStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("finance_status");

                    b.Property<decimal?>("GrossProfit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("gross_profit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("LastCustomerUpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_customer_update_date");

                    b.Property<DateTimeOffset?>("LastInternalCommentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_internal_comment_date");

                    b.Property<DateOnly?>("LoadingDate")
                        .HasColumnType("date")
                        .HasColumnName("loading_date");

                    b.Property<DateOnly?>("NextActionDate")
                        .HasColumnType("date")
                        .HasColumnName("next_action_date");

                    b.Property<string>("NextActionDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("next_action_description");

                    b.Property<long?>("NextActionOwnerId")
                        .HasColumnType("bigint")
                        .HasColumnName("next_action_owner_id");

                    b.Property<string>("OriginCity")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("origin_city");

                    b.Property<string>("OriginCountry")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("origin_country");

                    b.Property<DateOnly?>("PaymentDueDate")
                        .HasColumnType("date")
                        .HasColumnName("payment_due_date");

                    b.Property<DateOnly?>("PaymentReceivedDate")
                        .HasColumnType("date")
                        .HasColumnName("payment_received_date");

                    b.Property<DateOnly?>("PlannedDeliveryDate")
                        .HasColumnType("date")
                        .HasColumnName("planned_delivery_date");

                    b.Property<long?>("ResponsibleUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("responsible_user_id");

                    b.Property<decimal?>("RevenueAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("revenue_amount");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("risk_level");

                    b.Property<long?>("SalesOwnerId")
                        .HasColumnType("bigint")
                        .HasColumnName("sales_owner_id");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("service_type");

                    b.Property<string>("Shipper")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("shipper");

                    b.Property<long?>("SourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceOperationNo")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("source_operation_no");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<string>("TradeDirection")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("trade_direction");

                    b.Property<string>("TransportType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("transport_type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_operations");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_operations_customer_id");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_operations_department_id");

                    b.HasIndex("Eta")
                        .HasDatabaseName("ix_operations_eta");

                    b.HasIndex("NextActionOwnerId")
                        .HasDatabaseName("ix_operations_next_action_owner_id");

                    b.HasIndex("ResponsibleUserId")
                        .HasDatabaseName("ix_operations_responsible_user_id");

                    b.HasIndex("RiskLevel")
                        .HasDatabaseName("ix_operations_risk_level");

                    b.HasIndex("SalesOwnerId")
                        .HasDatabaseName("ix_operations_sales_owner_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_operations_status");

                    b.HasIndex("TransportType")
                        .HasDatabaseName("ix_operations_transport_type");

                    b.HasIndex("SourceId", "SourceOperationNo")
                        .IsUnique()
                        .HasDatabaseName("ix_operations_source_id_source_operation_no");

                    b.ToTable("operations", (string)null);
                });

            modelBuilder.Entity("Ols.ControlCenter.Domain.Entities.OperationDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Airline")
                        .HasColumnType("text")
                        .HasColumnName("airline");

                    b.Property<string>("ArrivalAirport")
                        .HasColumnType("text")
                        .HasColumnName("arrival_airport");

                    b.Property<string>("BlNo")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("bl_no");

                    b.Property<string>("BorderCrossing")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("border_crossing");

                    b.Property<string>("CargoType")
                        .HasColumnType("text")
                        .HasColumnName("cargo_type");

                    b.Property<string>("ContainerNo")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("container_no");

                    b.Property<string>("ContainerType")
                        .HasColumnType("text")
                        .HasColumnName("container_type");

                    b.Property<int?>("DemurrageRiskDays")
                        .HasColumnType("integer")
                        .HasColumnName("demurrage_risk_days");

                    b.Property<DateOnly?>("DemurrageStartDate")
                        .HasColumnType("date")
                        .HasColumnName("demurrage_start_date");

                    b.Property<string>("DepartureAirport")
                        .HasColumnType("text")
                        .HasColumnName("departure_airport");

                    b.Property<string>("DriverName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("driver_name");

                    b.Property<string>("ExtraAttributes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("extra_attributes");

                    b.Property<decimal?>("FillRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("fill_rate");

                    b.Property<string>("FlightNo")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("flight_no");

                    b.Property<DateOnly?>("FreeTimeEndDate")
                        .HasColumnType("date")
                        .HasColumnName("free_time_end_date");

                    b.Property<decimal?>("GrossWeightKg")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("gross_weight_kg");

                    b.Property<string>("HawbNo")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("hawb_no");

                    b.Property<decimal?>("Ldm")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("ldm");

                    b.Property<string>("MawbNo")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("mawb_no");

                    b.Property<long>("OperationId")
                        .HasColumnType("bigint")
                        .HasColumnName("operation_id");

                    b.Property<string>("OrdinoStatus")
                        .HasColumnType("text")
                        .HasColumnName("ordino_status");

                    b.Property<int?>("Pieces")
                        .HasColumnType("integer")
                        .HasColumnName("pieces");

                    b.Property<string>("Pod")
                        .HasColumnType("text")
                        .HasColumnName("pod");

                    b.Property<string>("Pol")
                        .HasColumnType("text")
                        .HasColumnName("pol");

                    b.Property<string>("ShippingLine")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("shipping_line");

                    b.Property<string>("TransshipmentPort")
                        .HasColumnType("text")
                        .HasColumnName("transshipment_port");

                    b.Property<string>("VehiclePlate")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("vehicle_plate");

                    b.Property<string>("VesselName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("vessel_name");

                    b.Property<decimal?>("VolumeM3")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("volume_m3");

                    b.Property<decimal?>("VolumeWeightKg")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("volume_weight_kg");

                    b.Property<decimal?>("WeightKg")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("weight_kg");

                    b.HasKey("Id")
                        .HasName("pk_operation_details");

                    b.HasIndex("BlNo")
                        .HasDatabaseName("ix_operation_details_bl_no");

                    b.HasIndex("ContainerNo")
                        .HasDatabaseName("ix_operation_details_container_no");

                    b.HasIndex("OperationId")
                        .IsUnique()
                        .HasDatabaseName("ix_operation_details_operation_id");

                    b.ToTable("operation_details", (string)null);
                });

            modelBuilder.Entity("Ols.ControlCenter.Domain.Entities.Payment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Bank")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("bank");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasDefaultValue("EUR")
                        .HasColumnName("currency");

                    b.Property<long?>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("customer_name");

                    b.Property<int>("DelayDays")
                        .HasColumnType("integer")
                        .HasColumnName("delay_days");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<long?>("FinanceUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("finance_user_id");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("invoice_no");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<long?>("OperationId")
                        .HasColumnType("bigint")
                        .HasColumnName("operation_id");

                    b.Property<DateOnly?>("ReceivedDate")
                        .HasColumnType("date")
                        .HasColumnName("received_date");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("risk_level");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_payments_customer_id");

                    b.HasIndex("DueDate")
                        .HasDatabaseName("ix_payments_due_date");

                    b.HasIndex("FinanceUserId")
                        .HasDatabaseName("ix_payments_finance_user_id");

                    b.HasIndex("InvoiceNo")
                        .HasDatabaseName("ix_payments_invoice_no");

                    b.HasIndex("OperationId")
                        .HasDatabaseName("ix_payments_operation_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_payments_status");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("Ols.ControlCenter.Domain.Entities.RiskRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("alert_type");

                    b.Property<string>("AppliesToTransportType")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("applies_to_transport_type");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("Parameters")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("parameters");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("severity");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_risk_rules");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_risk_rules_code");

                    b.ToTable("risk_rules", (string)null);
                });

            modelBuilder.Entity("Ols.ControlCenter.Domain.Entities.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_code");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Ols.ControlCenter.Domain.Entities.StatusHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<long?>("ChangedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("changed_by_user_id");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("from_status");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<long>("OperationId")
                        .HasColumnType("bigint")
                        .HasColumnName("operation_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("to_status");

                    b.HasKey("Id")
                        .HasName("pk_status_histories");

                    b.HasIndex("OperationId", "ChangedAt")
                        .HasDatabaseName("ix_status_histories_operation_id_changed_at");

                    b.ToTable("status_histories", (string)null);
                });

            modelBuilder.Entity("Ols.ControlCenter.Domain.Entities.StatusMapping", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("DataSourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("data_source_id");

                    b.Property<string>("SourceStatus")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("source_status");

                    b.Property<string>("TargetStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("target_status");

                    b.HasKey("Id")
                        .HasName("pk_status_mappings");

                    b.HasIndex("DataSourceId", "SourceStatus")
                        .HasDatabaseName("ix_status_mappings_data_source_id_source_status");

                    b.ToTable("status_mappings", (string)null);
                });

            modelBuilder.Entity("Ols.ControlCenter.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<long?>("DepartmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("department_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset?>("RefreshTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expires_at");

                    b.Property<string>("RefreshTokenHash")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("refresh_token_hash");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_users_department_id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Ols.ControlCenter.Domain.Entities.UserRole", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Ols.ControlCenter.Domain.Entities.WorkTask", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("CompletionNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("completion_note");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<long?>("DepartmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("department_id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<long?>("OperationId")
                        .HasColumnType("bigint")
                        .HasColumnName("operation_id");

                    b.Property<long?>("OwnerUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("priority");

                    b.Property<long?>("SourceAlertId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_alert_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_work_tasks");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_work_tasks_department_id");

                    b.HasIndex("OperationId")
                        .HasDatabaseName("ix_work_tasks_operation_id");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_work_tasks_owner_user_id");

                    b.HasIndex("Status", "DueDate")
                        .HasDatabaseName("ix_work_tasks_status_due_date");

                    b.ToTable("work_tasks", (string)null);
                });

            modelBuilder.Entity("Ols.ControlCenter.Domain.Entities.Alert", b =>
                {
                    b.HasOne("Ols.ControlCenter.Domain.Entities.Operation", "Operation")
                        .WithMany("Alerts")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_alerts_operations_operation_id");

                    b.HasOne("Ols.ControlCenter.Domain.Entities.User", "ResponsibleUser")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_alerts_users_responsible_user_id");

                    b.Navigation("Operation");

                    b.Navigation("ResponsibleUser");
                });

            modelBuilder.Entity("Ols.ControlCenter.Domain.Entities.Comment", b =>
                {
                    b.HasOne("Ols.ControlCenter.Domain.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_comments_users_author_user_id");

                    b.HasOne("Ols.ControlCenter.Domain.Entities.Operation", "Operation")
                        .WithMany("Comments")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comments_operations_operation_id");

                    b.Navigation("Author");

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("Ols.ControlCenter.Domain.Entities.DataSource", b =>
                {
                    b.HasOne("Ols.ControlCenter.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_data_sources_departments_department_id");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Ols.ControlCenter.Domain.Entities.DataSourceColumnMapping", b =>
                {
                    b.HasOne("Ols.ControlCenter.Domain.Entities.DataSource", "DataSource")
                        .WithMany("ColumnMappings")
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_data_source_column_mappings_data_sources_data_source_id");

                    b.Navigation("DataSource");
                });

            modelBuilder.Entity("Ols.ControlCenter.Domain.Entities.DataSyncLog", b =>
                {
                    b.HasOne("Ols.ControlCenter.Domain.Entities.DataSource", "DataSource")
                        .WithMany("SyncLogs")
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_data_sync_logs_data_sources_data_source_id");

                    b.Navigation("DataSource");
                });

            modelBuilder.Entity("Ols.ControlCenter.Domain.Entities.Document", b =>
                {
                    b.HasOne("Ols.ControlCenter.Domain.Entities.Operation", "Operation")
                        .WithMany("Documents")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_documents_operations_operation_id");

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("Ols.ControlCenter.Domain.Entities.Notification", b =>
                {
                    b.HasOne("Ols.ControlCenter.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ols.ControlCenter.Domain.Entities.Operation", b =>
                {
                    b.HasOne("Ols.ControlCenter.Domain.Entities.Customer", "Customer")
                        .WithMany("Operations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_operations_customers_customer_id");

                    b.HasOne("Ols.ControlCenter.Domain.Entities.Department", "Department")
                        .WithMany("Operations")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_operations_departments_department_id");

                    b.HasOne("Ols.ControlCenter.Domain.Entities.User", "NextActionOwner")
                        .WithMany()
                        .HasForeignKey("NextActionOwnerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_operations_users_next_action_owner_id");

                    b.HasOne("Ols.ControlCenter.Domain.Entities.User", "ResponsibleUser")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_operations_users_responsible_user_id");

                    b.HasOne("Ols.ControlCenter.Domain.Entities.User", "SalesOwner")
                        .WithMany()
                        .HasForeignKey("SalesOwnerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_operations_users_sales_owner_id");

                    b.HasOne("Ols.ControlCenter.Domain.Entities.DataSource", "Source")
                        .WithMany("Operations")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_operations_data_sources_source_id");

                    b.Navigation("Customer");

                    b.Navigation("Department");

                    b.Navigation("NextActionOwner");

                    b.Navigation("ResponsibleUser");

                    b.Navigation("SalesOwner");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("Ols.ControlCenter.Domain.Entities.OperationDetail", b =>
                {
                    b.HasOne("Ols.ControlCenter.Domain.Entities.Operation", "Operation")
                        .WithOne("Detail")
                        .HasForeignKey("Ols.ControlCenter.Domain.Entities.OperationDetail", "OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_operation_details_operations_operation_id");

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("Ols.ControlCenter.Domain.Entities.Payment", b =>
                {
                    b.HasOne("Ols.ControlCenter.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_payments_customers_customer_id");

                    b.HasOne("Ols.ControlCenter.Domain.Entities.User", "FinanceUser")
                        .WithMany()
                        .HasForeignKey("FinanceUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_payments_users_finance_user_id");

                    b.HasOne("Ols.ControlCenter.Domain.Entities.Operation", "Operation")
                        .WithMany("Payments")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_payments_operations_operation_id");

                    b.Navigation("Customer");

                    b.Navigation("FinanceUser");

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("Ols.ControlCenter.Domain.Entities.StatusHistory", b =>
                {
                    b.HasOne("Ols.ControlCenter.Domain.Entities.Operation", "Operation")
                        .WithMany("StatusHistory")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_status_histories_operations_operation_id");

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("Ols.ControlCenter.Domain.Entities.StatusMapping", b =>
                {
                    b.HasOne("Ols.ControlCenter.Domain.Entities.DataSource", "DataSource")
                        .WithMany("StatusMappings")
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_status_mappings_data_sources_data_source_id");

                    b.Navigation("DataSource");
                });

            modelBuilder.Entity("Ols.ControlCenter.Domain.Entities.User", b =>
                {
                    b.HasOne("Ols.ControlCenter.Domain.Entities.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_users_departments_department_id");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Ols.ControlCenter.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("Ols.ControlCenter.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("Ols.ControlCenter.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ols.ControlCenter.Domain.Entities.WorkTask", b =>
                {
                    b.HasOne("Ols.ControlCenter.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_work_tasks_departments_department_id");

                    b.HasOne("Ols.ControlCenter.Domain.Entities.Operation", "Operation")
                        .WithMany("Tasks")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_work_tasks_operations_operation_id");

                    b.HasOne("Ols.ControlCenter.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_work_tasks_users_owner_user_id");

                    b.Navigation("Department");

                    b.Navigation("Operation");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Ols.ControlCenter.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Operations");
                });

            modelBuilder.Entity("Ols.ControlCenter.Domain.Entities.DataSource", b =>
                {
                    b.Navigation("ColumnMappings");

                    b.Navigation("Operations");

                    b.Navigation("StatusMappings");

                    b.Navigation("SyncLogs");
                });

            modelBuilder.Entity("Ols.ControlCenter.Domain.Entities.Department", b =>
                {
                    b.Navigation("Operations");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Ols.ControlCenter.Domain.Entities.Operation", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Comments");

                    b.Navigation("Detail");

                    b.Navigation("Documents");

                    b.Navigation("Payments");

                    b.Navigation("StatusHistory");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Ols.ControlCenter.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Ols.ControlCenter.Domain.Entities.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
